### ISSUE TITLE
Stroke attribute

### ISSUE THREAD

**Issue by alexantr** [colebemis/feather#11]
New icons have stroke attribute in inner elements instead outer <svg>. Is that normal case?

P.S. "box", "link-2" and "package" icons have stroke color `#0f0f0f` instead `#000`

**Comment by colebemis** [comment]
In v2.1.0, I started using SVGO so the new icons now have `stroke` and other attributes applied to the elements of the SVG instead of the SVG tag itself. This new approach speeds up development time by quite a bit. I plan to make the older icons follow this same pattern for consistency.

Can you think of any reasons why applying attributes to the SVG tag (the old way) might be better than the contents of the SVG (the new way)? 

Also, thanks for catching the #0f0f0f! I'll fix that right now.

**Comment by alexantr** [comment]
> Can you think of any reasons why applying attributes to the SVG tag (the old way) might be better than the contents of the SVG (the new way)?

I think there is no difference. I still can change stroke color by CSS: `svg * { stroke: currentColor; }` instead `svg { stroke: currentColor; }`.

But with attributes in `<svg>` tag icons have a little bit smaller size if they have more than one element.
For example updated icon `user` has 364 bytes. After moving attributes to `<svg>` it will have 274 bytes.

**Comment by colebemis** [comment]
The stroke color of `box`, `link-2` and `package` have been fixed on the `v2.2.0` branch. Thanks for pointing that out!

**Comment by lukepighetti** [comment]
Stroke isn't coming into Affinity Designer. Not sure why.

**Comment by MarcelloTheArcane** [comment]
This is an issue for me. I am using it with a modified `vue-feather-icons` implementation for nuxt, which results in this:

```html
Vue: 
<feather-settings />

Rendered:
<svg>...</svg>
```
It makes it a lot easier to style if the `stroke`, `stroke-width`, and `fill` are on the svg element:

```html
<feather-settings stroke-width="1" stroke="#2d3748" />
```
