### ISSUE TITLE
Icon Request: Crop

### ISSUE THREAD

**Issue by colebemis** [colebemis/feather#152]
Name: Crop
Use Case: Used for photo editing.
(I think we all know what a crop icon looks like 😉)

**Comment by thiagotomasi** [comment]
Hey @colebemis, how are you?
I can help with this one!
Can we contribute or should I wait to you finish the 'design guidelines and contribution instructions.'?

**Comment by colebemis** [comment]
@thiagotomasi I have a very specific process for adding icons that I haven't documented yet. Because of this, at the moment we are not accepting pull requests containing icons **but that doesn't mean you can't contribute**. The best way to contribute an icon is to create an issue with a screenshot and link to an SVG of your icon. If I use your design, I'll document it and make sure you get credit 👍

**Comment by thiagotomasi** [comment]
@colebemis, awesome!!!
Thanks for your quick reply!!! 😄

**Comment by thiagotomasi** [comment]
Hey @colebemis, here it is!!!
[crop-icon.zip](https://github.com/colebemis/feather/files/1156807/crop-icon.zip)

I made 2 options, following the same style, round border, strokes, and size of the other ones,
you can choose which one you want, my choice would be the 'crop.svg' because it is more simple and closer to the others.

crop.svg
![crop](https://user-images.githubusercontent.com/4387026/28331211-e07096ca-6bf8-11e7-9d67-9d45a6a88e22.png)
crop-2.svg
![crop-2](https://user-images.githubusercontent.com/4387026/28331216-e61cb5e0-6bf8-11e7-9e89-5481de38871f.png) 

And please, if you want any change or fix, just let me know.
