### ISSUE TITLE
Error in console on page load

### ISSUE THREAD

**Issue by yashghelani** [colebemis/feather#165]
Every time I refresh my project page, I get this error in my console -  
![screen shot 2017-08-09 at 6 22 20 am](https://user-images.githubusercontent.com/26831728/29100724-2a7f1970-7ccb-11e7-9b93-c1e20ad6e801.png)

**Comment by colebemis** [comment]
Can you show me the code that caused this error?

**Comment by yashghelani** [comment]
I'm using the icon font using this script -
![screen shot 2017-08-10 at 3 46 31 am](https://user-images.githubusercontent.com/26831728/29146407-96aa717c-7d7e-11e7-9bcb-71614f71791c.png)

**Comment by colebemis** [comment]
Try using this instead and see if that still gives you an error: 
```html
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>

// instead of 

<script src="https://unpkg.com/feather-icons"></script>

```

**Comment by yashghelani** [comment]
Wow! Your solution worked. There is no error in the console and it also hugely improved the load time. Can you explain me what was the problem here?

**Comment by colebemis** [comment]
Great! The problem is that `https://unpkg.com/feather-icons` is a shortcut that points to `feather.js` which has a relative path to its source map. However, `https://unpkg.com/feather.js.map` doesn't exist. By using the long URL (`https://unpkg.com/feather-icons/dist/feather.min.js`) instead of the shortcut, the relative path to the source map is correct. Also, I gave you the link to the minified version which is probably why it's faster.

I'll update the docs so no one else runs into this issue 👍

**Comment by yashghelani** [comment]
Cool! Thanks 😄
