### ISSUE TITLE
Blank page using the example provided

### ISSUE THREAD

**Issue by bebosudo** [colebemis/feather#176]
Hey, I'd like to use your icons in a project of mine.
I cloned your repo, tried opening your example [feather/examples/index.html](https://github.com/colebemis/feather/blob/0e70a99e8ac41aa268a0880c06805dad822bfb91/examples/index.html) with firefox 55.0, but the page is blank.

Looking at the source, it tries to load the js from `../dist/feather.min.js`, but there's not (no more?) a folder named `dist` in your repo.
Changing the src attribute/parameter to
`<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>`
did the job.

Thanks for the icons!

**Comment by tohjustin** [comment]
@bebosudo You probably haven't build the files, which is why you were not able to see a `/dist` directory.

To get the `/dist` in your repo, run the following commands in the terminal:
```bash
git clone https://github.com/colebemis/feather.git && cd feather
npm install
npm run build
```
You should see the following files in your `/dist` directory & you would be able to see the icons when you open [feather/examples/index.html](https://github.com/colebemis/feather/blob/master/examples/index.html):
```bash
dist
├── feather.js
├── feather.js.map
├── feather.min.js
├── feather.min.js.map
├── icons
└── icons.json
```

**Comment by colebemis** [comment]
@bebosudo Yeah, that's probably the problem. Alternatively, you could  run `npm run all` to generate the `/dist` directory *and* confirm that there are no linting errors. Both `npm run build` and `npm run all` should fix this problem.

**Comment by bebosudo** [comment]
Hi!
Thanks for the reply: I'm not a js developer and it looks like I don't have npm installed on my system (Fedora 25) to test it.
Anyway thanks for the tip.

I'm going to publish a PR to improve this example with a small clarification.
