### ISSUE TITLE
Search icon inconsistency

### ISSUE THREAD

**Issue by colmtuite** [colebemis/feather#5]
The circle in the "Search" icon is 15px x 15px. The circles in the "Zoom in" and "Zoom out" icons are 16px x 16px. Aside from the glyphs inside the circle, these icons seem like they should be otherwise identical? Am I missing something? Or making a false assumption?

**Comment by colebemis** [comment]
The reason I made the `search` and `zoom` circles different is because the dimensions of the `zoom` circle need to be *even* in order to center the `+` and `-`. I thought that 16x16 circle looked a little too large for `search` because there there's nothing inside the circle. 15x15 seemed to work pretty well for search.

Can you think of any scenarios where the different sizes might cause problems?

**Comment by colmtuite** [comment]
I don't think there would be a specific, isolated scenario where it might cause problems, just that the inconsistency is a problem in itself.

I actually prefer the 16px circle for `search`, I like the added weight on the glass of the magnifying glass-it adds legibility I think, especially at a smaller 16px size.

Not a big deal but certainly an inconsistency imo.

**Comment by colebemis** [comment]
I really appreciate the suggestion but I think I'm going to leave them as-is for now. I'll continue to think about it though.
